#!/bin/bash
#
#    Print ID for the latest version of a mercurial commit
#    Copyright (C) 2018  Marco Leogrande
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

function usage () {
  echo "$(basename ${0}) REVISION" >&2
  echo '  Prints on stdout the latest version of a mercurial commit.' >&2
}

if [[ -z "$1" ]]; then
  usage
  exit 0
fi

if ! [[ "$1" == '.' || "$1" =~ ^[0-9a-f]+$ ]]; then
  echo "'${1}' is not a valid revision." >&2
  exit 1
fi

result="$(hg log -T '{node}\n' -r "successors(${1})" --hidden | tail -1)"
if [[ -z "${result}" ]]; then
  echo "Failed to determine latest revision for '${1}'." >&2
  exit 1
fi

echo "${result}"
exit 0
